### ISSUE TITLE
Usando imagem ao invés de fonte para o logotipo

### ISSUE THREAD

**Issue by juanpinheiro** [Unacon/StarWars#1]
Esse é sim um dos pontos mais desafiadores deste código! Existe uma propriedade chamada background-clip para criar o efeito na fonte! =)

![image](https://user-images.githubusercontent.com/8218229/112075326-0d827080-8b57-11eb-98d4-90059b4cc6cd.png)

As imagens usando % com um background image, você pode distorcer essa imagem e perder sua qualidade
![image](https://user-images.githubusercontent.com/8218229/112145869-a77b0500-8bb9-11eb-8ff4-9dc851522501.png)

**Comment by juanpinheiro** [comment]
Usar um max-width pode ajudar em monitores grandes.

```html
<section class="characters">
    <div class="container">
            ...
    </div>
</section>
```

```css
.container {
    width: 100%;
    max-width: 1280px;
    margin: 0 auto;
    ...
}

```
